### ISSUE TITLE
No scroll-snap compatibility

### ISSUE THREAD

**Issue by markusand** [donmbelembe/vue-dragscroll#64]
It doesn't seem to work when using css scroll-snap-align

```css
.carousel {
	position: relative;
	display: flex;
	height: 500px;
	width: 100%;
	scroll-snap-type: x mandatory;
	overflow-x: auto;

	/* Hide scrollbar */
	-ms-overflow-style: none;
	scrollbar-width: none;
	&::-webkit-scrollbar {
		display: none;
	}
}

.carousel .slide {
	flex: 0 0 100%;
	height: 100%;
	position: relative;
	box-sizing: border-box;
	scroll-snap-align: center;        <--- Here is the problem
	scroll-snap-stop: always;
}
```

Is there any way to make it work?
